### ISSUE TITLE
What is the difference between first and latest edition of the model architecture?

### ISSUE THREAD

**Issue by l6chen** [zeroone-universe/RealTimeBWE#2]
Hello, 

While I was reproducing the result, I found that the latest model could not generate valid high frequency part with small part of vctk dataset (i.e. one speaker). After I used all the vctk dataset to train the latest model, it converge in 10 epochs.

**Comment by l6chen** [comment]
And then I pull the codes from the first commit and run the same experiment like before, it can converge anyway in 10 epoch. So I am wondering why did you modify the model and are they both casual?

**Comment by zeroone-universe** [comment]
Hi,

since this repo is unofficial, there were some deviations from the original paper's structure in the early stages of implementation. The final version addresses these issues as much as possible. There is no significant difference in performance, though.

To the best of my recollection, there were no big difference between the generator part (and their causality) of first and latest commit, except for their scalability. 

Best.

**Comment by l6chen** [comment]
Thanks! And I notice the discriminator is enlarged in the final commit where the groups are smaller in the MelGAN. Maybe that's reason why it needs more data to train. I will follow the latest commit code to finetune my model.
Thanks again for your work!
