### ISSUE TITLE
About checkpoints

### ISSUE THREAD

**Issue by Bridge-SR** [zeroone-universe/RealTimeBWE#5]
Hi! Good work, and I am wonderinig if the checkpoints can be shared? I really desire it!

**Comment by Bridge-SR** [comment]
I am also query about whether it support SR to 44.1 or 48kHz?

**Comment by zeroone-universe** [comment]
Hi, thanks for your interest in this repo.

I am wonderinig if the checkpoints can be shared?
-> It's been a long time since I worked on this research, and unfortunately, I no longer have the checkpoints saved.

I am also query about whether it support SR to 44.1 or 48kHz?
-> This model only supports bandwidth extension from 8kHz to 16kHz and does not handle other sample rates. If you want to extend the bandwidth to 44.1kHz, you will need to modify both the model and the training code. To be honest, even with these modifications, I don't believe extending the bandwidth from 8kHz to 44.1kHz with this model will produce good results.
